import { defaultLocale } from '@/middleware';
import '@/styles/global.css';
import type { Metadata } from 'next';
import { Be_Vietnam_Pro } from 'next/font/google';
import Header from '../components/Header';

const beVietnam = Be_Vietnam_Pro({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-be-vietnam-pro',
	style: 'normal',
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
	params,
}: {
	children: React.ReactNode;
	params: { lang: string };
}) {
	return (
		<html lang={params.lang ?? defaultLocale} id="app">
			<body className={beVietnam.className}>
				<video
					preload="false"
					autoPlay
					loop
					muted
					playsInline
					className="video-hero"
				>
					<source src="./assets/videos/hero.webm" type="video/webm" />
				</video>
				<Header lang={params.lang ?? defaultLocale} />
				{children}
			</body>
		</html>
	);
}
